- name: Demo on facts 
  hosts: all 
  gather_facts: false                # By default, this value is true
  tasks:
    - name: Printing a fact  
      ansible.builtin.debug:
        msg: "CPU Architectire is {{ansible_architecture}}"