- name: Demo on tasks
  hosts: all 
  gather_facts: false
  tasks:
    - name: Installing frontend
      ansible.builtin.debug:
        msg: Installing frontend
      tags: frontend

    - name: starting frontend
      ansible.builtin.debug:
        msg: starting frontend
      tags: frontend

    - name: Installing backend
      ansible.builtin.debug:
        msg: Installing backend
      tags: backend

    - name: starting backend
      ansible.builtin.debug:
        msg: starting backend
      tags: backend

    - name: Installing mysql
      ansible.builtin.debug:
        msg: Installing mysql
      tags: mysql

    - name: starting mysql
      ansible.builtin.debug:
        msg: starting mysql
      tags: mysql

# ansible-playbook -i inv -e ansible_user=ec2-user -e ansible_password=DevOps321 -t mysql 006-tags.yml
# Run the playbook using above command where you are including the details of the tags