- name: Demo on using package 
  hosts: all    
  gather_facts: false 
  become: true # privilege escalation, (run as root user)
  tasks:
    - name: Installing Nginx 
      ansible.builtin.package:
       name: nginx
       state: present