- name: Configuring hostname 
  ansible.builtin.shell: set-hostname "{{COMPONENT}}-{{ENV}}"

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present 

- name: Copying proxy file 
  ansible.builtin.template:
    src: proxy.conf
    dest: /etc/nginx/default.d/expense.conf  

- name: Cleanup 
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent

- name: Creating App directory 
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: directory

- name: Download and extracts {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://expense-web-app.s3.amazonaws.com/{{COMPONENT}}.zip
    dest: "{{APP_PATH}}"
    remote_src: yes      # If mentioned no, it will be downloaded on the ansible server instead of remote server                       
# This defines that download and extract will happen on the remote node 
 

- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd_service:
    name: nginx 
    state: restarted
    enabled: true
    daemon_reload: true